export const seedData = {
  admin: {
    id: 1,
    name: 'Daniyal Khan',
    title: 'Full Stack Developer',
    email: 'admin@gmail.com',
    password: 'admin1234',
    phone: '+92 318 2315238',
    address: 'Karachi, Pakistan',
    avatar: 'profile.jpg',
    bio: 'I am a Full Stack Developer specializing in React, ASP.NET MVC, .NET Core, Node.js, and SQL Server with over 2 years of proven professional experience building high-performance web applications, API microservices, and interactive dashboards.',
    social: {
      github: 'https://github.com/inoxentdani09-web',
      linkedin: 'https://linkedin.com/in/daniyal-developer',
      twitter: 'https://twitter.com/daniyal_dev',
      facebook: 'https://facebook.com/daniyal.dev'
    },
    updatedAt: new Date().toISOString()
  },
  settings: {
    siteTitle: 'Daniyal | Full Stack Developer',
    tagline: 'A Full Stack Developer Who Builds Real, Working Solutions',
    heroHeading: "Hi, I'm Daniyal",
    heroSubheading: 'Full Stack Developer & Software Engineer',
    heroDescription: "I design and develop responsive websites, dynamic web applications, and desktop software — from pixel-perfect front-end designs with HTML5, CSS3, Tailwind CSS, and React, to robust back-end systems built with ASP.NET Core, Node.js, and SQL Server.",
    aboutHeading: 'Who I Am',
    aboutDescription: "I'm Daniyal, a passionate Full Stack Developer with a drive for building scalable, high-impact digital products. On the front end, I craft clean, interactive interfaces using modern frameworks. On the back end, I architect reliable databases and secure APIs. I am open to freelance contracts and full-time remote opportunities worldwide.",
    yearsExperience: '2+',
    completedProjects: 15,
    happyClients: 12,
    technologiesCount: 10,
    email: 'inoxentdani09@gmail.com',
    phone: '+92 318 2315238',
    location: 'Karachi, Pakistan',
    workingHours: 'Mon - Sat: 9:00 AM - 6:00 PM',
    darkThemeDefault: true,
    paymentAccounts: {
      jazzCashNumber: '0318-2315238',
      jazzCashTitle: 'Daniyal Khan',
      easyPaisaNumber: '0318-2315238',
      easyPaisaTitle: 'Daniyal Khan',
      bankName: 'Meezan Bank / HBL',
      bankAccountNumber: '0102-03182315238',
      bankIban: 'PK36MEZN00010203182315238',
      bankAccountTitle: 'Daniyal Khan',
      instructions: 'Please send course fee to any account above. After payment, enter Transaction ID (TID) and attach screenshot. Daniyal will verify and approve your course access.'
    }
  },
  categories: [
    { id: 1, name: 'Frontend', slug: 'frontend', type: 'skill', description: 'User interface & client-side technologies' },
    { id: 2, name: 'Backend', slug: 'backend', type: 'skill', description: 'Server-side runtimes & business logic' },
    { id: 3, name: 'Database', slug: 'database', type: 'skill', description: 'Data persistence & SQL engines' },
    { id: 4, name: 'Tools & Desktop', slug: 'tools', type: 'skill', description: 'Desktop software & development toolsets' },
    { id: 5, name: 'E-Commerce', slug: 'ecommerce', type: 'project', description: 'Online store and shopping cart platforms' },
    { id: 6, name: 'Dashboard', slug: 'dashboard', type: 'project', description: 'Admin portals and analytics panels' },
    { id: 7, name: 'Portfolio', slug: 'portfolio', type: 'project', description: 'Personal branding and portfolio showcases' },
    { id: 8, name: 'Desktop App', slug: 'desktop-app', type: 'project', description: 'Windows standalone applications' }
  ],
  skills: [
    {
      id: 1,
      categoryId: 1,
      categoryName: 'Frontend',
      name: 'HTML5',
      icon: 'HTML.png',
      level: 'Expert',
      proficiency: 95,
      status: 'Published',
      description: 'Semantic markup, accessibility (a11y), responsive structures, and SEO compliance.',
      createDate: '2024-01-10T10:00:00.000Z'
    },
    {
      id: 2,
      categoryId: 1,
      categoryName: 'Frontend',
      name: 'CSS3 / Tailwind',
      icon: 'CSS.png',
      level: 'Expert',
      proficiency: 92,
      status: 'Published',
      description: 'Modern flexbox, grid layouts, keyframe animations, mobile-first responsive architecture.',
      createDate: '2024-01-12T10:00:00.000Z'
    },
    {
      id: 3,
      categoryId: 1,
      categoryName: 'Frontend',
      name: 'JavaScript (ES6+)',
      icon: 'JS.png',
      level: 'Advanced',
      proficiency: 88,
      status: 'Published',
      description: 'Asynchronous programming, closures, DOM manipulation, promises, and modern API consumption.',
      createDate: '2024-01-15T10:00:00.000Z'
    },
    {
      id: 4,
      categoryId: 2,
      categoryName: 'Backend',
      name: 'C# .NET',
      icon: 'C-sharap.png',
      level: 'Advanced',
      proficiency: 90,
      status: 'Published',
      description: 'Object-oriented architecture, LINQ, dependency injection, asynchronous tasks, and data streams.',
      createDate: '2024-02-01T10:00:00.000Z'
    },
    {
      id: 5,
      categoryId: 2,
      categoryName: 'Backend',
      name: 'ASP.NET Core MVC',
      icon: 'ASP.NET.png',
      level: 'Advanced',
      proficiency: 90,
      status: 'Published',
      description: 'MVC architectural patterns, RESTful APIs, EF Core ORM, security filters, and middleware pipelines.',
      createDate: '2024-02-10T10:00:00.000Z'
    },
    {
      id: 6,
      categoryId: 3,
      categoryName: 'Database',
      name: 'SQL Server',
      icon: 'SQL.png',
      level: 'Advanced',
      proficiency: 85,
      status: 'Published',
      description: 'Relational schema design, normalization, stored procedures, indexing, and query optimization.',
      createDate: '2024-02-18T10:00:00.000Z'
    },
    {
      id: 7,
      categoryId: 4,
      categoryName: 'Tools & Desktop',
      name: 'Desktop App Dev',
      icon: 'DekstopApplication.png',
      level: 'Intermediate',
      proficiency: 80,
      status: 'Published',
      description: 'Windows Forms & WPF software development with hardware interfaces and local database sync.',
      createDate: '2024-03-01T10:00:00.000Z'
    }
  ],
  projects: [
    {
      projectID: 1,
      categoryId: 5,
      category: 'E-Commerce',
      title: 'Full Stack E-Commerce Platform',
      technalogy: 'ASP.NET Core',
      techStack: ['ASP.NET Core', 'SQL Server', 'Entity Framework', 'Bootstrap 5', 'JavaScript'],
      status: 'Published',
      description: 'A scalable e-commerce platform with dynamic product catalogs, cart state management, user authentication, customer reviews, and administrative order tracking.',
      image: '673a38a1-fc24-4376-b538-d2d1100fad7b.png',
      gitHub: 'https://github.com/inoxentdani09-web/Dani-Portfolio',
      liveDemo: 'https://github.com/inoxentdani09-web/Dani-Portfolio',
      featured: true,
      createdDate: '2024-06-15T12:00:00.000Z'
    },
    {
      projectID: 2,
      categoryId: 7,
      category: 'Portfolio',
      title: 'Developer Portfolio & Admin CMS',
      technalogy: 'ASP.NET Core',
      techStack: ['Node.js', 'Express', 'EJS', 'Chart.js', 'Bootstrap 5', 'CSS3'],
      status: 'Published',
      description: 'A responsive developer portfolio featuring real-time client inquiry management, interactive skill matrix, live project showcase, and a secured administrative control panel.',
      image: '45a0cd2e-fec7-4578-89c6-3f5fb9993e5d.png',
      gitHub: 'https://github.com/inoxentdani09-web/Dani-Portfolio',
      liveDemo: 'https://github.com/inoxentdani09-web/Dani-Portfolio',
      featured: true,
      createdDate: '2024-07-20T14:30:00.000Z'
    },
    {
      projectID: 3,
      categoryId: 8,
      category: 'Dekstop Application',
      title: 'Point of Sale & Inventory System',
      technalogy: 'C#',
      techStack: ['C# .NET', 'Windows Forms', 'SQL Server', 'Crystal Reports'],
      status: 'Published',
      description: 'Desktop enterprise management solution for retail inventory, barcode scanning, instant receipt printing, supplier ledger tracking, and daily sales auditing.',
      image: '3cc79509-05eb-4d13-931d-63368f55ef43.png',
      gitHub: 'https://github.com/inoxentdani09-web/Dani-Portfolio',
      liveDemo: 'https://github.com/inoxentdani09-web/Dani-Portfolio',
      featured: true,
      createdDate: '2024-08-05T09:15:00.000Z'
    },
    {
      projectID: 4,
      categoryId: 6,
      category: 'Dashboard',
      title: 'Task & Workflow Collaboration Portal',
      technalogy: 'HTML/CSS/JavaScript',
      techStack: ['JavaScript', 'HTML5', 'CSS3', 'REST API', 'Local Storage'],
      status: 'Published',
      description: 'Team productivity tool for tracking project roadmaps, Kanban sprint boards, workload allocation, and real-time team milestone notifications.',
      image: '1eaa6302-ab9e-4365-a031-23673eddfa27.png',
      gitHub: 'https://github.com/inoxentdani09-web/Dani-Portfolio',
      liveDemo: 'https://github.com/inoxentdani09-web/Dani-Portfolio',
      featured: false,
      createdDate: '2024-09-01T16:45:00.000Z'
    }
  ],
  courses: [
    {
      courseID: 1,
      categoryId: 1,
      category: 'Frontend',
      courseName: 'HTML5 & Modern Semantic Web Architecture',
      priceType: 'free',
      price: 'Free',
      originalPrice: 'PKR 2,000',
      platform: 'Daniyal Dev Academy',
      instructor: 'Daniyal Khan',
      technology: 'HTML5',
      level: 'Beginner to Advanced',
      duration: '18 Hours',
      progress: 100,
      status: 'Completed',
      certificate: true,
      rating: 4.9,
      enrollments: 1420,
      courseUrl: '#',
      description: 'Master HTML5 semantics, web accessibility (a11y), modern forms, responsive media, SEO best practices, and DOM structure from scratch.',
      curriculum: [
        { title: 'Module 1: Semantic HTML & Page Architecture', lessons: ['Doctypes, Metadata & SEO Head tags', 'Semantic Tags (header, nav, main, section, article, footer)', 'Accessibility ARIA Roles & Best Practices'] },
        { title: 'Module 2: Advanced Forms & User Input', lessons: ['Input types (date, color, regex patterns)', 'Client-side validation & attributes', 'Custom form controls & File uploaders'] },
        { title: 'Module 3: Media, Canvas & Modern APIs', lessons: ['Responsive Images with srcset and picture', 'HTML5 Video/Audio & Subtitles', 'HTML5 Canvas & Geolocation APIs'] }
      ],
      interactiveLesson: {
        title: 'HTML5 Semantic Layout Quick-Start',
        codeSnippet: `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>Semantic Web Page</title>\n</head>\n<body>\n  <header>\n    <h1>Welcome to Daniyal Tech</h1>\n    <nav><ul><li><a href="#about">About</a></li></ul></nav>\n  </header>\n  <main>\n    <article>\n      <h2>Semantic HTML5 is Powerful</h2>\n      <p>Clean structure enables high SEO and accessibility.</p>\n    </article>\n  </main>\n  <footer>&copy; 2025 Daniyal Khan</footer>\n</body>\n</html>`,
        explanation: 'Semantic HTML tags provide meaningful context for search engines, web browsers, and screen readers.'
      },
      startDate: '2024-01-10T00:00:00.000Z',
      completionDate: '2024-02-15T00:00:00.000Z',
      createdDate: '2024-01-10T00:00:00.000Z'
    },
    {
      courseID: 2,
      categoryId: 1,
      category: 'Frontend',
      courseName: 'CSS3, Flexbox, Grid & Responsive UI Systems',
      priceType: 'free',
      price: 'Free',
      originalPrice: 'PKR 2,500',
      platform: 'Daniyal Dev Academy',
      instructor: 'Daniyal Khan',
      technology: 'CSS3 / Tailwind',
      level: 'Beginner to Advanced',
      duration: '24 Hours',
      progress: 100,
      status: 'Completed',
      certificate: true,
      rating: 4.95,
      enrollments: 1890,
      courseUrl: '#',
      description: 'Learn modern CSS layouts with Flexbox and CSS Grid, fluid responsive typography, keyframe animations, glassmorphism, and dark mode theming.',
      curriculum: [
        { title: 'Module 1: CSS Box Model & Modern Selectors', lessons: ['Specificity, Cascade & Custom Properties (Variables)', 'Box sizing, margins, padding, and pseudo-elements', 'Modern CSS reset standards'] },
        { title: 'Module 2: Master Flexbox & CSS Grid', lessons: ['Flex direction, justify, align & wrap rules', 'CSS Grid templates, auto-fit, auto-fill & minmax()', 'Building complex responsive application layouts'] },
        { title: 'Module 3: Animations & Design Systems', lessons: ['CSS transitions, transforms & cubic-bezier', 'Keyframe micro-interactions & ripple effects', 'Media queries for mobile, tablet, desktop, and 4K'] }
      ],
      interactiveLesson: {
        title: 'CSS Grid Responsive 3-Column Card Layout',
        codeSnippet: `.card-container {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n  gap: 24px;\n  padding: 20px;\n}\n.card {\n  background: #111827;\n  border: 1px solid rgba(249, 115, 22, 0.3);\n  border-radius: 12px;\n  padding: 20px;\n  color: #fff;\n  transition: transform 0.3s ease;\n}\n.card:hover {\n  transform: translateY(-6px);\n}`,
        explanation: 'Using auto-fit and minmax gives you a responsive grid with zero media queries.'
      },
      startDate: '2024-02-01T00:00:00.000Z',
      completionDate: '2024-03-10T00:00:00.000Z',
      createdDate: '2024-02-01T00:00:00.000Z'
    },
    {
      courseID: 3,
      categoryId: 1,
      category: 'Frontend',
      courseName: 'JavaScript (ES6+) & Modern Web Development',
      priceType: 'free',
      price: 'Free',
      originalPrice: 'PKR 3,000',
      platform: 'Daniyal Dev Academy',
      instructor: 'Daniyal Khan',
      technology: 'JavaScript',
      level: 'Intermediate to Advanced',
      duration: '32 Hours',
      progress: 95,
      status: 'Completed',
      certificate: true,
      rating: 4.92,
      enrollments: 2340,
      courseUrl: '#',
      description: 'Master modern JavaScript ES6+, arrow functions, closures, promises, Async/Await, Fetch API, DOM manipulation, and interactive dynamic applications.',
      curriculum: [
        { title: 'Module 1: JavaScript Fundamentals & ES6+ Core', lessons: ['Let/Const, Arrow Functions, Template Literals', 'Destructuring, Spread/Rest operators, Modules', 'Array higher-order methods (map, filter, reduce)'] },
        { title: 'Module 2: DOM Manipulation & Event Handling', lessons: ['Selecting & mutating DOM nodes dynamically', 'Event listeners, delegation & event bubbling', 'Building interactive components (modals, tabs, carousels)'] },
        { title: 'Module 3: Asynchronous JS & API Integration', lessons: ['Event Loop, Microtasks & Promises', 'Async/Await error handling with try/catch', 'Consuming REST APIs via Fetch & Axios'] }
      ],
      interactiveLesson: {
        title: 'Modern Async/Await REST API Consumer',
        codeSnippet: `async function fetchDeveloperData(username) {\n  try {\n    const response = await fetch(\`https://api.github.com/users/\${username}\`);\n    if (!response.ok) throw new Error('User not found');\n    const data = await response.json();\n    console.log('Developer Bio:', data.bio, 'Public Repos:', data.public_repos);\n    return data;\n  } catch (error) {\n    console.error('API Error:', error.message);\n  }\n}\n// Call function\nfetchDeveloperData('inoxentdani09-web');`,
        explanation: 'Async/Await creates clean, non-blocking asynchronous code for fetching live backend endpoints.'
      },
      startDate: '2024-03-01T00:00:00.000Z',
      completionDate: '2024-04-15T00:00:00.000Z',
      createdDate: '2024-03-01T00:00:00.000Z'
    },
    {
      courseID: 4,
      categoryId: 2,
      category: 'Backend',
      courseName: 'C# & Object-Oriented Programming (OOP) Masterclass',
      priceType: 'paid',
      price: 'PKR 3,500',
      priceUSD: '$25',
      originalPrice: 'PKR 6,000',
      platform: 'Daniyal Dev Academy',
      instructor: 'Daniyal Khan',
      technology: 'C# .NET',
      level: 'Beginner to Advanced',
      duration: '40 Hours',
      progress: 90,
      status: 'Completed',
      certificate: true,
      rating: 4.96,
      enrollments: 870,
      courseUrl: '#',
      description: 'Comprehensive C# mastery: OOP pillars (Encapsulation, Inheritance, Polymorphism, Abstraction), Generics, LINQ, Delegates, Events, Async Tasks, and Memory Management.',
      curriculum: [
        { title: 'Module 1: C# Syntax, Types & Control Flow', lessons: ['Data types, nullable reference types, pattern matching', 'Value types vs Reference types in memory stack/heap', 'Loops, switches & exception handling'] },
        { title: 'Module 2: Object-Oriented Architecture', lessons: ['Classes, Objects, Constructors & Finalizers', 'Inheritance, Interfaces & Abstract Classes', 'Polymorphism (Method Overriding & Overloading)'] },
        { title: 'Module 3: LINQ & Advanced C# Features', lessons: ['LINQ query syntax vs method syntax', 'Generics, Collections & IEnumerable', 'Delegates, Func, Action, Lambdas & Events', 'Multithreading & Async/Await with Task Parallel Library'] }
      ],
      startDate: '2024-04-01T00:00:00.000Z',
      completionDate: '2024-05-20T00:00:00.000Z',
      createdDate: '2024-04-01T00:00:00.000Z'
    },
    {
      courseID: 5,
      categoryId: 2,
      category: 'Backend',
      courseName: 'ASP.NET Core MVC & RESTful Web APIs Full Stack',
      priceType: 'paid',
      price: 'PKR 5,000',
      priceUSD: '$35',
      originalPrice: 'PKR 8,500',
      platform: 'Daniyal Dev Academy',
      instructor: 'Daniyal Khan',
      technology: 'ASP.NET Core',
      level: 'Advanced',
      duration: '50 Hours',
      progress: 100,
      status: 'Completed',
      certificate: true,
      rating: 4.98,
      enrollments: 940,
      courseUrl: '#',
      description: 'End-to-end ASP.NET Core 8 Web Development: MVC architecture, Dependency Injection, Middleware, REST APIs, JWT Auth, Swagger, and Deployment.',
      curriculum: [
        { title: 'Module 1: ASP.NET Core Fundamentals & Architecture', lessons: ['Program.cs, Request Middleware Pipeline, Kestrel', 'Dependency Injection (Transient, Scoped, Singleton)', 'Routing, Controllers, Action Results & Model Binding'] },
        { title: 'Module 2: RESTful Web APIs & Authentication', lessons: ['Building RESTful endpoints with DTOs & AutoMapper', 'JWT Authentication & Role-based Authorization', 'Global Exception Handling & Structured Logging with Serilog'] },
        { title: 'Module 3: Real-Time & Production Deployment', lessons: ['SignalR for real-time live bi-directional notifications', 'Docker containerization for .NET applications', 'Deploying to IIS Server & Azure Cloud App Services'] }
      ],
      startDate: '2024-05-15T00:00:00.000Z',
      completionDate: '2024-07-01T00:00:00.000Z',
      createdDate: '2024-05-15T00:00:00.000Z'
    },
    {
      courseID: 6,
      categoryId: 3,
      category: 'Database',
      courseName: 'SQL Server & Relational Database Architecture',
      priceType: 'paid',
      price: 'PKR 3,000',
      priceUSD: '$20',
      originalPrice: 'PKR 5,000',
      platform: 'Daniyal Dev Academy',
      instructor: 'Daniyal Khan',
      technology: 'SQL Server',
      level: 'Intermediate to Advanced',
      duration: '30 Hours',
      progress: 100,
      status: 'Completed',
      certificate: true,
      rating: 4.91,
      enrollments: 1120,
      courseUrl: '#',
      description: 'Design enterprise relational databases in Microsoft SQL Server: Normalization, Foreign Keys, Stored Procedures, Triggers, Views, Indexing, and Query Optimization.',
      curriculum: [
        { title: 'Module 1: Database Design & Normalization', lessons: ['Entity-Relationship Diagrams (ERD) & 1:1, 1:N, N:M Relations', '1NF, 2NF, 3NF Normalization rules', 'DDL & DML Commands (CREATE, ALTER, INSERT, UPDATE, DELETE)'] },
        { title: 'Module 2: Advanced T-SQL Queries & Joins', lessons: ['INNER, LEFT, RIGHT, FULL OUTER & CROSS Joins', 'Subqueries, CTEs (Common Table Expressions) & Window Functions', 'Aggregations, Grouping & Rollup analytics'] },
        { title: 'Module 3: Programmability & Performance Tuning', lessons: ['Stored Procedures with Input/Output parameters', 'User Defined Functions (Scalar & Table-valued)', 'DML & DDL Triggers for auditing', 'Clustered vs Non-Clustered Indexes & Execution Plans'] }
      ],
      startDate: '2024-06-01T00:00:00.000Z',
      completionDate: '2024-07-15T00:00:00.000Z',
      createdDate: '2024-06-01T00:00:00.000Z'
    },
    {
      courseID: 7,
      categoryId: 1,
      category: 'Frontend',
      courseName: 'Bootstrap 5 & Modern UI Design Systems',
      priceType: 'paid',
      price: 'PKR 2,500',
      priceUSD: '$18',
      originalPrice: 'PKR 4,000',
      platform: 'Daniyal Dev Academy',
      instructor: 'Daniyal Khan',
      technology: 'Bootstrap 5',
      level: 'Beginner to Intermediate',
      duration: '20 Hours',
      progress: 100,
      status: 'Completed',
      certificate: true,
      rating: 4.88,
      enrollments: 760,
      courseUrl: '#',
      description: 'Build fast, mobile-first responsive interfaces using Bootstrap 5 utility classes, grid systems, custom Sass theming, modals, accordions, and navigation bars.',
      curriculum: [
        { title: 'Module 1: Bootstrap 5 Grid & Flexbox Utilities', lessons: ['12-column grid container, row, col-xxl to col-sm', 'Flex utilities, spacing, margins & auto alignments', 'Typography, colors, badges and responsive buttons'] },
        { title: 'Module 2: Interactive Components & Modals', lessons: ['Navbars, Offcanvas mobile drawers & Dropdowns', 'Modals, Toasts, Tooltips & Alert dialogs', 'Forms, floating labels, validation states & input groups'] },
        { title: 'Module 3: Custom SCSS Theming & Production Build', lessons: ['Customizing Bootstrap variables with Sass', 'Dark mode integration with data-bs-theme', 'Minification, purge unused CSS & performance optimization'] }
      ],
      startDate: '2024-07-01T00:00:00.000Z',
      completionDate: '2024-07-28T00:00:00.000Z',
      createdDate: '2024-07-01T00:00:00.000Z'
    },
    {
      courseID: 8,
      categoryId: 2,
      category: 'Backend',
      courseName: 'Entity Framework Core 8 & LINQ Data Access',
      priceType: 'paid',
      price: 'PKR 4,000',
      priceUSD: '$28',
      originalPrice: 'PKR 7,000',
      platform: 'Daniyal Dev Academy',
      instructor: 'Daniyal Khan',
      technology: 'Entity Framework',
      level: 'Advanced',
      duration: '35 Hours',
      progress: 95,
      status: 'Completed',
      certificate: true,
      rating: 4.94,
      enrollments: 650,
      courseUrl: '#',
      description: 'Master modern ORM data engineering: Code-First & Database-First migrations, Fluent API configurations, Lazy vs Eager loading, Transactions, and Repository Patterns.',
      curriculum: [
        { title: 'Module 1: EF Core Setup & Code-First Migrations', lessons: ['DbContext configuration & Connection Strings in appsettings.json', 'DbSet entities, Data Annotations vs Fluent API', 'Add-Migration, Update-Database & rollback strategies'] },
        { title: 'Module 2: Relationships & Query Optimization', lessons: ['One-to-One, One-to-Many & Many-to-Many entity relationships', 'Eager Loading (.Include), Explicit Loading & Lazy Loading', 'AsNoTracking() for high-throughput read operations'] },
        { title: 'Module 3: Enterprise Architecture & Repositories', lessons: ['Generic Repository Pattern & Unit of Work in C#', 'Database Transactions & Concurrency Conflict handling', 'Raw SQL execution, Stored Procedure mapping & Dapper hybrid'] }
      ],
      startDate: '2024-08-01T00:00:00.000Z',
      completionDate: '2024-09-10T00:00:00.000Z',
      createdDate: '2024-08-01T00:00:00.000Z'
    },
    {
      courseID: 9,
      categoryId: 1,
      category: 'Frontend',
      courseName: 'React 19 & TypeScript Frontend Architecture',
      priceType: 'paid',
      price: 'PKR 4,500',
      priceUSD: '$32',
      originalPrice: 'PKR 8,000',
      platform: 'Daniyal Dev Academy',
      instructor: 'Daniyal Khan',
      technology: 'React & TypeScript',
      level: 'Advanced',
      duration: '45 Hours',
      progress: 85,
      status: 'In Progress',
      certificate: false,
      rating: 4.97,
      enrollments: 1280,
      courseUrl: '#',
      description: 'Build enterprise Single Page Applications with React 19, TypeScript strict typing, Custom Hooks, Context API, Redux Toolkit, and Tailwind CSS UI libraries.',
      curriculum: [
        { title: 'Module 1: React 19 Core & Hooks Mastery', lessons: ['JSX, Component Lifecycle, Props & Strict TypeScript interfaces', 'useState, useEffect, useMemo, useCallback, useRef, useId', 'New React 19 Actions, useTransition & useOptimistic'] },
        { title: 'Module 2: State Management & Routing', lessons: ['React Router v6 nested layouts, loaders & actions', 'Global state with Context API & Reducer pattern', 'Redux Toolkit (RTK) & RTK Query for caching server state'] },
        { title: 'Module 3: Full Stack Integration & Testing', lessons: ['Consuming ASP.NET Core & Node.js REST APIs', 'Authentication flow with JWT, HTTP cookies & protected routes', 'Performance profiling, code splitting with React.lazy'] }
      ],
      startDate: '2024-09-15T00:00:00.000Z',
      completionDate: null,
      createdDate: '2024-09-15T00:00:00.000Z'
    },
    {
      courseID: 10,
      categoryId: 2,
      category: 'Backend',
      courseName: 'Node.js, Express & RESTful Microservices',
      priceType: 'paid',
      price: 'PKR 4,500',
      priceUSD: '$32',
      originalPrice: 'PKR 7,500',
      platform: 'Daniyal Dev Academy',
      instructor: 'Daniyal Khan',
      technology: 'Node.js & Express',
      level: 'Intermediate to Advanced',
      duration: '38 Hours',
      progress: 90,
      status: 'In Progress',
      certificate: false,
      rating: 4.93,
      enrollments: 890,
      courseUrl: '#',
      description: 'Scalable backend runtime with Node.js & Express: Non-blocking I/O, MVC folder structures, JWT authentication, file uploads with Multer, and RESTful API endpoints.',
      curriculum: [
        { title: 'Module 1: Node.js Architecture & Express Routing', lessons: ['Event driven non-blocking I/O, Streams & Buffers', 'Express Router, Middleware stack & Request/Response cycle', 'Environment configuration with dotenv'] },
        { title: 'Module 2: File Handling, Uploads & Security', lessons: ['Multer multipart image/document file uploads', 'Rate limiting, CORS, Helmet security headers', 'Cookie session management & JWT Token verification'] },
        { title: 'Module 3: Database & Cloud Deployment', lessons: ['Connecting SQL & NoSQL databases', 'Building full CRUD endpoints with error boundaries', 'Deploying Express apps to Cloud Run, Render & VPS'] }
      ],
      startDate: '2024-10-01T00:00:00.000Z',
      completionDate: null,
      createdDate: '2024-10-01T00:00:00.000Z'
    },
    {
      courseID: 11,
      categoryId: 2,
      category: 'Full Stack',
      courseName: 'Complete Full-Stack Web Development Bootcamp (.NET + React + SQL)',
      priceType: 'paid',
      price: 'PKR 12,000',
      priceUSD: '$75',
      originalPrice: 'PKR 25,000',
      platform: 'Daniyal Dev Academy',
      instructor: 'Daniyal Khan',
      technology: 'Full Stack (.NET + React + SQL)',
      level: 'All Levels (Zero to Hero)',
      duration: '120 Hours',
      progress: 95,
      status: 'Completed',
      certificate: true,
      rating: 4.99,
      enrollments: 3200,
      courseUrl: '#',
      description: 'The ultimate all-in-one full-stack developer program: HTML5, CSS3, JavaScript, Bootstrap, C#, ASP.NET Core, SQL Server, Entity Framework, React, and 5 Real-world Capstone Projects.',
      curriculum: [
        { title: 'Phase 1: Frontend Foundation (HTML, CSS, JS, Bootstrap)', lessons: ['Semantic HTML5, CSS Grid/Flexbox & Responsive design', 'Modern JavaScript ES6+ & DOM manipulation', 'Bootstrap 5 and custom styled interfaces'] },
        { title: 'Phase 2: Database Mastery (SQL Server & EF Core)', lessons: ['Relational database schema modeling & T-SQL queries', 'Stored Procedures, Triggers & Performance Indexing', 'Entity Framework Core 8 Code-First migrations'] },
        { title: 'Phase 3: Backend & Web APIs (C# & ASP.NET Core)', lessons: ['C# Object-Oriented Programming (OOP) masterclass', 'ASP.NET Core REST API design, JWT auth & DTO patterns', 'Repository pattern & Unit of Work implementation'] },
        { title: 'Phase 4: Modern Frontend & Full Stack Integration', lessons: ['React 19 SPA development with TypeScript & Redux', 'Connecting React to ASP.NET Core Web API backend', 'Capstone 1: E-Commerce Store with Payment Gateway', 'Capstone 2: Enterprise Admin Portal & Real-time Chat', 'DevOps: Docker containerization & Cloud production deploy'] }
      ],
      startDate: '2024-01-01T00:00:00.000Z',
      completionDate: '2024-11-20T00:00:00.000Z',
      createdDate: '2024-01-01T00:00:00.000Z'
    }
  ],
  messages: [
    {
      messageID: 1,
      name: 'Sarah Johnson',
      email: 'sarah.j@techvision.io',
      phone: '+1 415 555 2671',
      subject: 'Web Application Project Inquiry',
      messageText: 'Hi Daniyal, I saw your portfolio and was impressed by your ASP.NET Core and React projects. We have an upcoming client portal project and would love to discuss a freelance engagement.',
      status: 'Unread',
      isStarred: true,
      replied: false,
      replyText: '',
      createdDate: '2025-01-12T10:30:00.000Z'
    },
    {
      messageID: 2,
      name: 'Ahmed Khan',
      email: 'ahmed.khan@innovate.pk',
      phone: '+92 300 1234567',
      subject: 'Full Stack Developer Role',
      messageText: 'Hello Daniyal, we are looking for a skilled full stack developer to help us build a custom dashboard for our inventory system. Please let us know your availability.',
      status: 'Read',
      isStarred: false,
      replied: true,
      replyText: 'Hi Ahmed, thank you for reaching out! I am available for new freelance projects. Let us schedule a call.',
      createdDate: '2025-01-08T15:20:00.000Z'
    }
  ]
};
